src/survey/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from excercise.views import Home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home, name="project_list"),
    url(r'^', include('excercise.urls')),
    url(r'^', include('dashboard.urls')),
    url(r'^accounts/', include("accounts.urls")),
]

src/excercise/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save, post_save
# Create your models here.

class Project(models.Model):
	project_name = models.CharField(max_length = 100)
	created_by 	 = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
	created_at   = models.DateTimeField(auto_now = True,auto_now_add = False)
	updated      = models.DateTimeField(auto_now = False,auto_now_add = True)

	def __str__(self):
		return self.project_name


class Excercise(models.Model):
	project 	   = models.ForeignKey(Project,on_delete=models.CASCADE,null = True,blank = True)
	excercise_name = models.CharField(max_length = 100)
	created_by     = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
	created_at     = models.DateTimeField(auto_now = True,auto_now_add = False)
	updated        = models.DateTimeField(auto_now = False,auto_now_add = True)

	def __str__(self):
		return self.excercise_name

ANSWER_CHOICE = (
    ('Binary', 'Binary'),
    ('Numeric', 'Numeric'),
    ('Choice', 'Choice Filed'),
    ('Textbox', 'Textbox')
)

class NumericRadioFormat(models.Model):
	title = models.CharField(max_length=50)
	numeric1 = models.CharField(max_length=50, null=True, blank=True)
	numeric2 = models.CharField(max_length=50, null=True, blank=True)
	numeric3 = models.CharField(max_length=50, null=True, blank=True)
	numeric4 = models.CharField(max_length=50, null=True, blank=True)
	numeric5 = models.CharField(max_length=50, null=True, blank=True)
	numeric6 = models.CharField(max_length=50, null=True, blank=True)
	numeric7 = models.CharField(max_length=50, null=True, blank=True)
	numeric8 = models.CharField(max_length=50, null=True, blank=True)
	numeric9 = models.CharField(max_length=50, null=True, blank=True)
	numeric10 = models.CharField(max_length=50, null=True, blank=True)

	def __str__(self):
		return self.title

class ChoiceItemFormat(models.Model):
	title = models.CharField(max_length=50)
	item1 = models.CharField(max_length=50, null=True, blank=True)
	item2 = models.CharField(max_length=50, null=True, blank=True)
	item3 = models.CharField(max_length=50, null=True, blank=True)

	def __str__(self):
		return self.title

class BinaryFormat(models.Model):
	title = models.CharField(max_length=50)
	item1 = models.CharField(max_length=50, null=True, blank=True)
	item2 = models.CharField(max_length=50, null=True, blank=True)

	def __str__(self):
		return self.title

class Question(models.Model):
	excercise 	= models.ForeignKey(Excercise,on_delete=models.CASCADE)
	title 		= models.CharField(max_length = 150)
	description = models.TextField()
	answer_format = models.CharField(max_length=20,choices=ANSWER_CHOICE)
	numeric_format = models.ForeignKey(NumericRadioFormat,on_delete=models.CASCADE,null = True,blank = True)
	choice_item_format = models.ForeignKey(ChoiceItemFormat,on_delete=models.CASCADE,null = True,blank = True)
	binary_format = models.ForeignKey(BinaryFormat,on_delete=models.CASCADE,null = True,blank = True)
	additional_box = models.BooleanField(default=False)
	def __str__(self):
		return self.title


class AssignExcercise(models.Model):
	user         = models.ForeignKey(User,on_delete=models.CASCADE)
	excercise 	 = models.ForeignKey(Excercise,on_delete=models.CASCADE)
	assign_at    = models.DateTimeField(auto_now = True,auto_now_add = False)
	answered = models.BooleanField(default=False)
	def __str__(self):
		return self.user.username

def take_q_receiver(sender,created, instance, *args, **kwargs):
	if created:
		LastTakeQuestion.objects.create(assign=instance)
post_save.connect(take_q_receiver, sender=AssignExcercise)


class LastTakeQuestion(models.Model):
	assign = models.OneToOneField(AssignExcercise,on_delete=models.CASCADE, related_name="lqt")
	page = models.IntegerField(default=1)

	def __str__(self):
		return str(self.id)



class QuestionAnswer(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	assign = models.ForeignKey(AssignExcercise, on_delete=models.CASCADE, related_name="answerq")
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	answer = models.TextField(null=True,blank=True)
	additional_answer = models.TextField(null=True,blank=True)
	answer_at = models.DateTimeField(auto_now = True,auto_now_add = False)
	

	def __str__(self):
		return self.question.title

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Survey</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/survey-style.css' %}" rel="stylesheet">

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>

    <script src="{% static 'js/radio/jQuery.select2OptionPicker.js' %}"></script>

    <link href="{% static 'js/radio/select2OptionPicker.css' %}" rel="stylesheet">
    <link href="{% static 'js/radio/style.css' %}" rel="stylesheet">


  </head>

  <body>
    

    <div class="wrapper">
  <div class="row">
    
    <!-- main -->
    <div class="column col-xs-10" id="main">
      {% block content %}

      {% endblock %}
    </div>

    <!-- sidebar -->
    <div class="column col-xs-2" id="sidebar" style="padding-right: 0px;padding-left: 0px;">
      {% include "sidebar.html" %}
      
      
    </div>
    
  </div>

</div>

    {% block body_js %}
    {% endblock %}

  </body>

</html>

src/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="page-header">
    <h1>Hello, {{ request.user.first_name }} {{ request.user.last_name }}</h1>      
  </div>
  <p>Last login: {{ request.user.last_login }}</p> 
  <a href="{% url 'logout' %}"><button type="button" class="btn btn-primary">Logout</button></a>        
  <a href="{% url 'change_password' %}"><button type="button" class="btn btn-primary">Change Password</button></a>        
</div>
{% endblock %}

src/templates/sidebar.html
  <ul class="list-group">
  	<li class="list-group-item" style="border-radius: 0px;background-color: #aeaeae;">Excercises</li>
  	{%  for excercise in assign_excercise %}
    	<li class="list-group-item" style="border-radius: 0px;background-color: #eee;"><a href="{% url 'excercise-details' excercise.id %}">{{ excercise.excercise.excercise_name }}</a></li>
    {% empty %}
	<li class="list-group-item" style="border-radius: 0px;background-color: #eee;">No excercises</li>
    {%  endfor %}
	<li class="list-group-item" style="border-radius: 0px;background-color: #aeaeae;">Menu</li>

	<li class="list-group-item" style="border-radius: 0px;background-color: #eee;"><a href="/">Home</a></li>
	<li class="list-group-item" style="border-radius: 0px;background-color: #eee;"><a href="{% url 'logout' %}">Logout</a></li>
  </ul>

src/templates/test.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block body_js %}'
  <script>
    $('.standard-demo').select2OptionPicker();
  </script>
{% endblock %}

{% block content %}


<div class="col-sm-12">

{% for question in ex_page %}

  <div class="page-header">
    <h1>{{ question.title }}</h1>      
  </div>
  <p>{{ question.description|linebreaks }}</p>
  <form method="post" action="{% if ansform.instance.id %} {% url 'question-answer-update' ansform.instance.id %} {% else %} {% url 'question-answer' %}{% endif %}" id="ans_form_id">{% csrf_token %}

  <input type="hidden" name="user" id="id_user" value="{{ request.user.id }}">
  <input type="hidden" name="question" id="id_question" value="{{ question.id }}">
  <input type="hidden" name="assign" id="id_assign" value="{{ assign_obj.id }}">
  <input type="hidden" name="assign" id="id_answer_format" value="{{ question.answer_format }}">
  <input type="hidden" name="crntpage" id="id_crnt_page" value="{{ current }}">
      <div>
        {% if question.answer_format == "Binary" %}

          <select name="preselected-select" class="standard-demo" id="binary_value">
          {% if question.binary_format.item1 %}
          <option {% if ansform.instance.answer == question.binary_format.item1 %} selected="" {% endif %} value="{{ question.binary_format.item1 }}">{{ question.binary_format.item1 }}</option>
          {% endif %}
          {% if question.binary_format.item2 %}
          <option {% if ansform.instance.answer == question.binary_format.item2 %} selected="" {% endif %} value="{{ question.binary_format.item2 }}" >{{ question.binary_format.item2 }}</option>
          {% endif %}
          </select>

        {% elif question.answer_format == "Numeric" %}


          <select class="standard-demo" id="numeric_value">
          {% if question.numeric_format.numeric1 %}
          <option value="1" {% if ansform.instance.answer == "1" %} selected="" {% endif %}>1</option>
          {% endif %}
          {% if question.numeric_format.numeric2 %}
          <option value="2" {% if ansform.instance.answer == "2" %} selected="" {% endif %}>2</option>
          {% endif %}
          {% if question.numeric_format.numeric3 %}
          <option value="3" {% if ansform.instance.answer == "3" %} selected="" {% endif %}>3</option>
          {% endif %}
          {% if question.numeric_format.numeric4 %}
          <option value="4" {% if ansform.instance.answer == "4" %} selected="" {% endif %}>4</option>
          {% endif %}
          {% if question.numeric_format.numeric5 %}
          <option value="5" {% if ansform.instance.answer == "5" %} selected="" {% endif %}>5</option>
          {% endif %}
          {% if question.numeric_format.numeric6 %}
          <option value="6" {% if ansform.instance.answer == "6" %} selected="" {% endif %}>6</option>
          {% endif %}
          {% if question.numeric_format.numeric7 %}
          <option value="7" {% if ansform.instance.answer == "7" %} selected="" {% endif %}>7</option>
          {% endif %}
          {% if question.numeric_format.numeric8 %}
          <option value="8" {% if ansform.instance.answer == "8" %} selected="" {% endif %}>8</option>
          {% endif %}
          {% if question.numeric_format.numeric9 %}
          <option value="9" {% if ansform.instance.answer == "9" %} selected="" {% endif %}>9</option>
          {% endif %}
          {% if question.numeric_format.numeric10 %}
          <option value="10" {% if ansform.instance.answer == "10" %} selected="" {% endif %}>10</option>
          {% endif %}
          </select>

<div class="select2OptionPicker"><ul class="select-buttons">
          {% if question.numeric_format.numeric1 %}<li>{{  question.numeric_format.numeric1 }}</li>{% endif %}

          {% if question.numeric_format.numeric2 %}<li>{{  question.numeric_format.numeric2 }}</li>{% endif %}

          {% if question.numeric_format.numeric3 %}<li>{{  question.numeric_format.numeric3 }}</li>{% endif %}

          {% if question.numeric_format.numeric4 %}<li>{{  question.numeric_format.numeric4 }}</li>{% endif %}

          {% if question.numeric_format.numeric5 %}<li>{{  question.numeric_format.numeric1 }}</li>{% endif %}

          {% if question.numeric_format.numeric6 %}<li>{{  question.numeric_format.numeric6 }}</li>{% endif %}

          {% if question.numeric_format.numeric7 %}<li>{{  question.numeric_format.numeric7 }}</li>{% endif %}

          {% if question.numeric_format.numeric8 %}<li>{{  question.numeric_format.numeric8 }}</li>{% endif %}

          {% if question.numeric_format.numeric9 %}<li>{{  question.numeric_format.numeric9 }}</li>{% endif %}

          {% if question.numeric_format.numeric10 %}<li>{{  question.numeric_format.numeric10 }}</li>{% endif %}


</ul>



</div>

        {% elif question.answer_format == "Choice" %}


          <select id="choice_value" class="standard-demo">
          {% if question.choice_item_format.item1 %}
          <option {% if ansform.instance.answer == question.choice_item_format.item1 %} selected="" {% endif %} value="{{ question.choice_item_format.item1 }}">{{ question.choice_item_format.item1 }}</option>
          {% endif %}
          {% if question.choice_item_format.item1 %}
          <option {% if ansform.instance.answer == question.choice_item_format.item2 %} selected="" {% endif %} value="{{ question.choice_item_format.item2 }}">{{ question.choice_item_format.item2 }}</option>
          {% endif %}
          {% if question.choice_item_format.item3 %}
          <option {% if ansform.instance.answer == question.choice_item_format.item3 %} selected="" {% endif %} value="{{ question.choice_item_format.item3 }}">{{ question.choice_item_format.item3 }}</option>
          {% endif %}
          </select>

        {% elif question.answer_format == "Textbox" %}
          <div class="textbox">
            {% render_field ansform.answer class="form-control" style="display: inline;margin-top: 15px" rows="2" %}
          </div>  
        {% endif %}



      </div>
      {% if question.additional_box %}

        <div class="additional">
          {% render_field ansform.additional_answer class="form-control" style="display: inline;margin-top: 15px" rows="2" %}
        </div>
      {% endif %}


      <div class="col-sm-12" style="margin-top: 50px;background-color: #cbc0c04d;padding: 13px;">
        {% if ex_page.has_other_pages %}

        {% if ex_page.has_previous %}
        <a href="?question={{ ex_page.previous_page_number }}"><button class="btn btn-info" type="button">BACK</button></a>
        {% endif %}
        {% if ex_page.has_next %}
          <a href="?question={{ ex_page.next_page_number }}" class="pull-right"><button class="btn btn-info" type="submit">SAVE</button></a>
          <input type="hidden" value="?question={{ ex_page.next_page_number }}" id="nexturl">
        <a href="?question={{ ex_page.next_page_number }}" class="pull-right"><button class="btn btn-info" type="button" style="margin-right: 10px">SKIP</button></a>
        {% else %}
        <input type="hidden" value="/" id="nexturl">
        <a href="" class="pull-right"><button class="btn btn-info" type="submit">COMPLETE</button></a>
        {% endif %}

        {% endif %}
      </div>
  </form>

{% empty %}
<p>404</p>
{% endfor %}

</div>



<footer class="footer" style="z-index: 99">
  <div class="col-sm-6" style="margin-top: 10px;">
  <small>{{ current }} of {{ total }} questions</small>
 <div class="progress" style="margin-bottom: 0px;">

  <div data-percentage="0%" style="width: {{ completep }}%;" class="progress-bar progress-bar-success" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
</div>
</div>
<div class="col-sm-6" style="margin-top: 5px;">
  <p class="pull-right" style="color: #535353e6;">
    <b>{{ request.user.first_name }} {{ request.user.last_name }}</b><br>
    <b>{{ today|date:'l dS M' }}</b>
  </p>
</div>
</footer>

{% endblock %}